const actionType = {
  ADMIN_REGISTER_NULL: 'ADMIN_REGISTER_NULL',
  ADMIN_REGISTER_SUCCESS: 'ADMIN_REGISTER_SUCCESS',
  ADMIN_REGISTER_FAILURE: 'ADMIN_REGISTER_FAILURE',
  GET_ALL_BOOKING_TODAY_SUCCESS: 'GET_ALL_BOOKING_TODAY_SUCCESS',
  GET_ALL_BOOKING_TODAY_FAILURE: 'GET_ALL_BOOKING_TODAY_FAILURE',
  ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
  ADMIN_LOGIN_FAILURE: 'ADMIN_LOGIN_FAILURE',
  ADMIN_LOGIN_NULL: 'ADMIN_LOGIN_NULL',
  GET_ALL_BOOKING_SUCCESS: 'GET_ALL_BOOKING_SUCCESS',
  GET_ALL_BOOKING_FAILURE: 'GET_ALL_BOOKING_FAILURE',
  GET_ALL_TIMESSLOTS_SUCCESS: 'GET_ALL_TIMESSLOTS_SUCCESS',
  GET_ALL_TIMESSLOTS_FAILURE: 'GET_ALL_TIMESSLOTS_FAILURE',
  BOOKING_SUCCESS: 'BOOKING_SUCCESS',
  BOOKING_FAILURE: 'BOOKING_FAILURE',
  BOOKING_NULL: 'BOOKING_NULL',
  GET_SETTING_SUCCESS: 'GET_SETTING_SUCCESS',
  GET_SETTING_FAILURE: 'GET_SETTING_FAILURE',
  GET_GRAPH_DATA_SUCCESS: 'GET_GRAPH_DATA_SUCCESS',
  GET_GRAPH_DATA_FAILURE: 'GET_GRAPH_DATA_FAILURE'
};

export default actionType;
